<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' == ''">$(MSBuildProjectDirectory)\..\lib</WssArtifactDir>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' != ''">$(WSS_ARTIFACT_DIR)</WssArtifactDir>
    <WssBleArtifactDir Condition="'$(WSS_BLE_ARTIFACT_DIR)' == ''">$(MSBuildProjectDirectory)\..\lib</WssBleArtifactDir>
    <WssBleArtifactDir Condition="'$(WSS_BLE_ARTIFACT_DIR)' != ''">$(WSS_BLE_ARTIFACT_DIR)</WssBleArtifactDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.44" />
    <PackageReference Include="System.Security.Permissions" Version="7.0.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WSS_Core_Interface">
      <HintPath>$(WssArtifactDir)\WSS_Core_Interface.dll</HintPath>
    </Reference>
    <Reference Include="WSS.Transport.BLE">
      <HintPath>$(WssBleArtifactDir)\WSS.Transport.BLE.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(WssArtifactDir)\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
