<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' == ''">$(MSBuildProjectDirectory)\..\lib</WssArtifactDir>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' != ''">$(WSS_ARTIFACT_DIR)</WssArtifactDir>
    <WssBleArtifactDir Condition="'$(WSS_BLE_ARTIFACT_DIR)' == ''">$(MSBuildProjectDirectory)\..\lib</WssBleArtifactDir>
    <WssBleArtifactDir Condition="'$(WSS_BLE_ARTIFACT_DIR)' != ''">$(WSS_BLE_ARTIFACT_DIR)</WssBleArtifactDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="WSS_Core_Interface">
      <HintPath>$(WssArtifactDir)\WSS_Core_Interface.dll</HintPath>
    </Reference>
    <Reference Include="WSS.Transport.BLE">
      <HintPath>$(WssBleArtifactDir)\WSS.Transport.BLE.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(WssArtifactDir)\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Ports">
      <HintPath>$(WssBleArtifactDir)\System.IO.Ports.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>$(WssBleArtifactDir)\System.Security.Permissions.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Extensions">
      <HintPath>$(WssBleArtifactDir)\System.Windows.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing.Common">
      <HintPath>$(WssBleArtifactDir)\System.Drawing.Common.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Win32.SystemEvents">
      <HintPath>$(WssBleArtifactDir)\Microsoft.Win32.SystemEvents.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(WssBleArtifactDir)/*.dll"
          Link="%(Filename)%(Extension)"
          TargetPath="%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(WssBleArtifactDir)/backends/**/*"
          Link="backends/%(RecursiveDir)%(Filename)%(Extension)"
          TargetPath="backends/%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(WssBleArtifactDir)/runtimes/**/*"
          Link="runtimes/%(RecursiveDir)%(Filename)%(Extension)"
          TargetPath="runtimes/%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
